/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'status' : ActivityStatus,
  'title' : string,
  'activityType' : ActivityType,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'dealId' : [] | [bigint],
  'contactId' : [] | [bigint],
}
export type ActivityStatus = { 'pending' : null } |
  { 'done' : null };
export type ActivityType = { 'call' : null } |
  { 'task' : null } |
  { 'email' : null } |
  { 'meeting' : null };
export interface Contact {
  'id' : bigint,
  'status' : ContactStatus,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'company' : string,
  'phone' : string,
}
export type ContactStatus = { 'customer' : null } |
  { 'lead' : null } |
  { 'inactive' : null } |
  { 'prospect' : null };
export interface Deal {
  'id' : bigint,
  'title' : string,
  'value' : number,
  'createdAt' : bigint,
  'expectedCloseDate' : string,
  'stage' : DealStage,
  'contactId' : bigint,
}
export type DealStage = { 'closedWon' : null } |
  { 'proposal' : null } |
  { 'negotiation' : null } |
  { 'qualified' : null } |
  { 'newLead' : null } |
  { 'closedLost' : null };
export interface Note {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'dealId' : [] | [bigint],
  'contactId' : [] | [bigint],
}
export interface Stats {
  'contactsByStatus' : Array<[ContactStatus, bigint]>,
  'dealsByStage' : Array<[DealStage, bigint]>,
  'totalPipelineValue' : number,
  'pendingActivitiesCount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<
    [ActivityType, string, string, [] | [bigint], [] | [bigint], string],
    bigint
  >,
  'createContact' : ActorMethod<
    [string, string, string, string, ContactStatus],
    bigint
  >,
  'createDeal' : ActorMethod<
    [string, bigint, number, DealStage, string],
    bigint
  >,
  'createNote' : ActorMethod<[string, [] | [bigint], [] | [bigint]], bigint>,
  'deleteActivity' : ActorMethod<[bigint], undefined>,
  'deleteContact' : ActorMethod<[bigint], undefined>,
  'deleteDeal' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'getActivity' : ActorMethod<[bigint], Activity>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllDeals' : ActorMethod<[], Array<Deal>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[bigint], Contact>,
  'getDeal' : ActorMethod<[bigint], Deal>,
  'getNote' : ActorMethod<[bigint], Note>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markActivityDone' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateActivity' : ActorMethod<
    [
      bigint,
      ActivityType,
      string,
      string,
      [] | [bigint],
      [] | [bigint],
      string,
      ActivityStatus,
    ],
    undefined
  >,
  'updateContact' : ActorMethod<
    [bigint, string, string, string, string, ContactStatus],
    undefined
  >,
  'updateDeal' : ActorMethod<
    [bigint, string, bigint, number, DealStage, string],
    undefined
  >,
  'updateDealStage' : ActorMethod<[bigint, DealStage], undefined>,
  'updateNote' : ActorMethod<
    [bigint, string, [] | [bigint], [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];