/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'call' : IDL.Null,
  'task' : IDL.Null,
  'email' : IDL.Null,
  'meeting' : IDL.Null,
});
export const ContactStatus = IDL.Variant({
  'customer' : IDL.Null,
  'lead' : IDL.Null,
  'inactive' : IDL.Null,
  'prospect' : IDL.Null,
});
export const DealStage = IDL.Variant({
  'closedWon' : IDL.Null,
  'proposal' : IDL.Null,
  'negotiation' : IDL.Null,
  'qualified' : IDL.Null,
  'newLead' : IDL.Null,
  'closedLost' : IDL.Null,
});
export const ActivityStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'status' : ActivityStatus,
  'title' : IDL.Text,
  'activityType' : ActivityType,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'dealId' : IDL.Opt(IDL.Nat),
  'contactId' : IDL.Opt(IDL.Nat),
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'status' : ContactStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'value' : IDL.Float64,
  'createdAt' : IDL.Int,
  'expectedCloseDate' : IDL.Text,
  'stage' : DealStage,
  'contactId' : IDL.Nat,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'dealId' : IDL.Opt(IDL.Nat),
  'contactId' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Stats = IDL.Record({
  'contactsByStatus' : IDL.Vec(IDL.Tuple(ContactStatus, IDL.Nat)),
  'dealsByStage' : IDL.Vec(IDL.Tuple(DealStage, IDL.Nat)),
  'totalPipelineValue' : IDL.Float64,
  'pendingActivitiesCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func(
      [
        ActivityType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ContactStatus],
      [IDL.Nat],
      [],
    ),
  'createDeal' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, DealStage, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'deleteDeal' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [Contact], ['query']),
  'getDeal' : IDL.Func([IDL.Nat], [Deal], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markActivityDone' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateActivity' : IDL.Func(
      [
        IDL.Nat,
        ActivityType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        ActivityStatus,
      ],
      [],
      [],
    ),
  'updateContact' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ContactStatus],
      [],
      [],
    ),
  'updateDeal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, DealStage, IDL.Text],
      [],
      [],
    ),
  'updateDealStage' : IDL.Func([IDL.Nat, DealStage], [], []),
  'updateNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'call' : IDL.Null,
    'task' : IDL.Null,
    'email' : IDL.Null,
    'meeting' : IDL.Null,
  });
  const ContactStatus = IDL.Variant({
    'customer' : IDL.Null,
    'lead' : IDL.Null,
    'inactive' : IDL.Null,
    'prospect' : IDL.Null,
  });
  const DealStage = IDL.Variant({
    'closedWon' : IDL.Null,
    'proposal' : IDL.Null,
    'negotiation' : IDL.Null,
    'qualified' : IDL.Null,
    'newLead' : IDL.Null,
    'closedLost' : IDL.Null,
  });
  const ActivityStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'status' : ActivityStatus,
    'title' : IDL.Text,
    'activityType' : ActivityType,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'dealId' : IDL.Opt(IDL.Nat),
    'contactId' : IDL.Opt(IDL.Nat),
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'status' : ContactStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'value' : IDL.Float64,
    'createdAt' : IDL.Int,
    'expectedCloseDate' : IDL.Text,
    'stage' : DealStage,
    'contactId' : IDL.Nat,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'dealId' : IDL.Opt(IDL.Nat),
    'contactId' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Stats = IDL.Record({
    'contactsByStatus' : IDL.Vec(IDL.Tuple(ContactStatus, IDL.Nat)),
    'dealsByStage' : IDL.Vec(IDL.Tuple(DealStage, IDL.Nat)),
    'totalPipelineValue' : IDL.Float64,
    'pendingActivitiesCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func(
        [
          ActivityType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ContactStatus],
        [IDL.Nat],
        [],
      ),
    'createDeal' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, DealStage, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Nat], [], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'deleteDeal' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [Contact], ['query']),
    'getDeal' : IDL.Func([IDL.Nat], [Deal], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markActivityDone' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateActivity' : IDL.Func(
        [
          IDL.Nat,
          ActivityType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          ActivityStatus,
        ],
        [],
        [],
      ),
    'updateContact' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ContactStatus],
        [],
        [],
      ),
    'updateDeal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, DealStage, IDL.Text],
        [],
        [],
      ),
    'updateDealStage' : IDL.Func([IDL.Nat, DealStage], [], []),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };