/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Note {
    id: bigint;
    content: string;
    createdAt: bigint;
    dealId?: bigint;
    contactId?: bigint;
}
export interface Activity {
    id: bigint;
    status: ActivityStatus;
    title: string;
    activityType: ActivityType;
    createdAt: bigint;
    dueDate: string;
    description: string;
    dealId?: bigint;
    contactId?: bigint;
}
export interface Contact {
    id: bigint;
    status: ContactStatus;
    name: string;
    createdAt: bigint;
    email: string;
    company: string;
    phone: string;
}
export interface Deal {
    id: bigint;
    title: string;
    value: number;
    createdAt: bigint;
    expectedCloseDate: string;
    stage: DealStage;
    contactId: bigint;
}
export interface Stats {
    contactsByStatus: Array<[ContactStatus, bigint]>;
    dealsByStage: Array<[DealStage, bigint]>;
    totalPipelineValue: number;
    pendingActivitiesCount: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ActivityStatus {
    pending = "pending",
    done = "done"
}
export enum ActivityType {
    call = "call",
    task = "task",
    email = "email",
    meeting = "meeting"
}
export enum ContactStatus {
    customer = "customer",
    lead = "lead",
    inactive = "inactive",
    prospect = "prospect"
}
export enum DealStage {
    closedWon = "closedWon",
    proposal = "proposal",
    negotiation = "negotiation",
    qualified = "qualified",
    newLead = "newLead",
    closedLost = "closedLost"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createActivity(activityType: ActivityType, title: string, description: string, contactId: bigint | null, dealId: bigint | null, dueDate: string): Promise<bigint>;
    createContact(name: string, email: string, phone: string, company: string, status: ContactStatus): Promise<bigint>;
    createDeal(title: string, contactId: bigint, value: number, stage: DealStage, expectedCloseDate: string): Promise<bigint>;
    createNote(content: string, contactId: bigint | null, dealId: bigint | null): Promise<bigint>;
    deleteActivity(id: bigint): Promise<void>;
    deleteContact(id: bigint): Promise<void>;
    deleteDeal(id: bigint): Promise<void>;
    deleteNote(id: bigint): Promise<void>;
    getActivity(id: bigint): Promise<Activity>;
    getAllActivities(): Promise<Array<Activity>>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllDeals(): Promise<Array<Deal>>;
    getAllNotes(): Promise<Array<Note>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContact(id: bigint): Promise<Contact>;
    getDeal(id: bigint): Promise<Deal>;
    getNote(id: bigint): Promise<Note>;
    getStats(): Promise<Stats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markActivityDone(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateActivity(id: bigint, activityType: ActivityType, title: string, description: string, contactId: bigint | null, dealId: bigint | null, dueDate: string, status: ActivityStatus): Promise<void>;
    updateContact(id: bigint, name: string, email: string, phone: string, company: string, status: ContactStatus): Promise<void>;
    updateDeal(id: bigint, title: string, contactId: bigint, value: number, stage: DealStage, expectedCloseDate: string): Promise<void>;
    updateDealStage(id: bigint, stage: DealStage): Promise<void>;
    updateNote(id: bigint, content: string, contactId: bigint | null, dealId: bigint | null): Promise<void>;
}
import type { Activity as _Activity, ActivityStatus as _ActivityStatus, ActivityType as _ActivityType, Contact as _Contact, ContactStatus as _ContactStatus, Deal as _Deal, DealStage as _DealStage, Note as _Note, Stats as _Stats, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createActivity(arg0: ActivityType, arg1: string, arg2: string, arg3: bigint | null, arg4: bigint | null, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(to_candid_ActivityType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(to_candid_ActivityType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createContact(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ContactStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0, arg1, arg2, arg3, to_candid_ContactStatus_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0, arg1, arg2, arg3, to_candid_ContactStatus_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createDeal(arg0: string, arg1: bigint, arg2: number, arg3: DealStage, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeal(arg0, arg1, arg2, to_candid_DealStage_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeal(arg0, arg1, arg2, to_candid_DealStage_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createNote(arg0: string, arg1: bigint | null, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteActivity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteContact(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteDeal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeal(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getActivity(arg0: bigint): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_Activity_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_Activity_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeals();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeals();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: bigint): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return from_candid_Contact_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return from_candid_Contact_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeal(arg0: bigint): Promise<Deal> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeal(arg0);
                return from_candid_Deal_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeal(arg0);
            return from_candid_Deal_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNote(arg0: bigint): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_Note_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_Note_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_Stats_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_Stats_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markActivityDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markActivityDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markActivityDone(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateActivity(arg0: bigint, arg1: ActivityType, arg2: string, arg3: string, arg4: bigint | null, arg5: bigint | null, arg6: string, arg7: ActivityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, to_candid_ActivityType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_ActivityStatus_n40(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, to_candid_ActivityType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_ActivityStatus_n40(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateContact(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ContactStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1, arg2, arg3, arg4, to_candid_ContactStatus_n6(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1, arg2, arg3, arg4, to_candid_ContactStatus_n6(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateDeal(arg0: bigint, arg1: string, arg2: bigint, arg3: number, arg4: DealStage, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeal(arg0, arg1, arg2, arg3, to_candid_DealStage_n8(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeal(arg0, arg1, arg2, arg3, to_candid_DealStage_n8(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateDealStage(arg0: bigint, arg1: DealStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDealStage(arg0, to_candid_DealStage_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDealStage(arg0, to_candid_DealStage_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNote(arg0: bigint, arg1: string, arg2: bigint | null, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_ActivityStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityStatus): ActivityStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ContactStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactStatus): ContactStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Contact_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contact): Contact {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DealStage_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStage): DealStage {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Stats_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stats): Stats {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ActivityStatus;
    title: string;
    activityType: _ActivityType;
    createdAt: bigint;
    dueDate: string;
    description: string;
    dealId: [] | [bigint];
    contactId: [] | [bigint];
}): {
    id: bigint;
    status: ActivityStatus;
    title: string;
    activityType: ActivityType;
    createdAt: bigint;
    dueDate: string;
    description: string;
    dealId?: bigint;
    contactId?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ActivityStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        activityType: from_candid_ActivityType_n14(_uploadFile, _downloadFile, value.activityType),
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        dealId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.dealId)),
        contactId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.contactId))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ContactStatus;
    name: string;
    createdAt: bigint;
    email: string;
    company: string;
    phone: string;
}): {
    id: bigint;
    status: ContactStatus;
    name: string;
    createdAt: bigint;
    email: string;
    company: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_ContactStatus_n21(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        company: value.company,
        phone: value.phone
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    value: number;
    createdAt: bigint;
    expectedCloseDate: string;
    stage: _DealStage;
    contactId: bigint;
}): {
    id: bigint;
    title: string;
    value: number;
    createdAt: bigint;
    expectedCloseDate: string;
    stage: DealStage;
    contactId: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        value: value.value,
        createdAt: value.createdAt,
        expectedCloseDate: value.expectedCloseDate,
        stage: from_candid_DealStage_n26(_uploadFile, _downloadFile, value.stage),
        contactId: value.contactId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    createdAt: bigint;
    dealId: [] | [bigint];
    contactId: [] | [bigint];
}): {
    id: bigint;
    content: string;
    createdAt: bigint;
    dealId?: bigint;
    contactId?: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        dealId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.dealId)),
        contactId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.contactId))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactsByStatus: Array<[_ContactStatus, bigint]>;
    dealsByStage: Array<[_DealStage, bigint]>;
    totalPipelineValue: number;
    pendingActivitiesCount: bigint;
}): {
    contactsByStatus: Array<[ContactStatus, bigint]>;
    dealsByStage: Array<[DealStage, bigint]>;
    totalPipelineValue: number;
    pendingActivitiesCount: bigint;
} {
    return {
        contactsByStatus: from_candid_vec_n36(_uploadFile, _downloadFile, value.contactsByStatus),
        dealsByStage: from_candid_vec_n38(_uploadFile, _downloadFile, value.dealsByStage),
        totalPipelineValue: value.totalPipelineValue,
        pendingActivitiesCount: value.pendingActivitiesCount
    };
}
function from_candid_tuple_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ContactStatus, bigint]): [ContactStatus, bigint] {
    return [
        from_candid_ContactStatus_n21(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DealStage, bigint]): [DealStage, bigint] {
    return [
        from_candid_DealStage_n26(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
}): ActivityStatus {
    return "pending" in value ? ActivityStatus.pending : "done" in value ? ActivityStatus.done : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    call: null;
} | {
    task: null;
} | {
    email: null;
} | {
    meeting: null;
}): ActivityType {
    return "call" in value ? ActivityType.call : "task" in value ? ActivityType.task : "email" in value ? ActivityType.email : "meeting" in value ? ActivityType.meeting : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    lead: null;
} | {
    inactive: null;
} | {
    prospect: null;
}): ContactStatus {
    return "customer" in value ? ContactStatus.customer : "lead" in value ? ContactStatus.lead : "inactive" in value ? ContactStatus.inactive : "prospect" in value ? ContactStatus.prospect : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closedWon: null;
} | {
    proposal: null;
} | {
    negotiation: null;
} | {
    qualified: null;
} | {
    newLead: null;
} | {
    closedLost: null;
}): DealStage {
    return "closedWon" in value ? DealStage.closedWon : "proposal" in value ? DealStage.proposal : "negotiation" in value ? DealStage.negotiation : "qualified" in value ? DealStage.qualified : "newLead" in value ? DealStage.newLead : "closedLost" in value ? DealStage.closedLost : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contact>): Array<Contact> {
    return value.map((x)=>from_candid_Contact_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ContactStatus, bigint]>): Array<[ContactStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DealStage, bigint]>): Array<[DealStage, bigint]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus): _ActivityStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ContactStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactStatus): _ContactStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DealStage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): _DealStage {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    call: null;
} | {
    task: null;
} | {
    email: null;
} | {
    meeting: null;
} {
    return value == ActivityType.call ? {
        call: null
    } : value == ActivityType.task ? {
        task: null
    } : value == ActivityType.email ? {
        email: null
    } : value == ActivityType.meeting ? {
        meeting: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus): {
    pending: null;
} | {
    done: null;
} {
    return value == ActivityStatus.pending ? {
        pending: null
    } : value == ActivityStatus.done ? {
        done: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactStatus): {
    customer: null;
} | {
    lead: null;
} | {
    inactive: null;
} | {
    prospect: null;
} {
    return value == ContactStatus.customer ? {
        customer: null
    } : value == ContactStatus.lead ? {
        lead: null
    } : value == ContactStatus.inactive ? {
        inactive: null
    } : value == ContactStatus.prospect ? {
        prospect: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): {
    closedWon: null;
} | {
    proposal: null;
} | {
    negotiation: null;
} | {
    qualified: null;
} | {
    newLead: null;
} | {
    closedLost: null;
} {
    return value == DealStage.closedWon ? {
        closedWon: null
    } : value == DealStage.proposal ? {
        proposal: null
    } : value == DealStage.negotiation ? {
        negotiation: null
    } : value == DealStage.qualified ? {
        qualified: null
    } : value == DealStage.newLead ? {
        newLead: null
    } : value == DealStage.closedLost ? {
        closedLost: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
